export const financialData = {
  totalRevenue: 152000,
  revenueChange: 12,
  expenses: 45000,
  expensesChange: 5,
  profit: 107000,
  profitChange: 15,
  pendingPayments: 35000,
  pendingPaymentsChange: -8,
  transactions: [
    {
      id: "TRX-1001",
      date: "Jul 24, 2023",
      description: "Booking Payment - ZT-1234",
      amount: 1200,
      type: "income",
      category: "booking",
      status: "completed",
      paymentMethod: "cash",
    },
    {
      id: "TRX-1002",
      date: "Jul 24, 2023",
      description: "Booking Payment - ZT-1235",
      amount: 1200,
      type: "income",
      category: "booking",
      status: "completed",
      paymentMethod: "online",
    },
    {
      id: "TRX-1003",
      date: "Jul 24, 2023",
      description: "Maintenance - Turf Cleaning",
      amount: 5000,
      type: "expense",
      category: "maintenance",
      status: "completed",
      paymentMethod: "cash",
    },
    {
      id: "TRX-1004",
      date: "Jul 25, 2023",
      description: "Booking Payment - ZT-1236",
      amount: 1200,
      type: "income",
      category: "booking",
      status: "completed",
      paymentMethod: "online",
    },
    {
      id: "TRX-1005",
      date: "Jul 25, 2023",
      description: "Booking Payment - ZT-1237",
      amount: 1200,
      type: "income",
      category: "booking",
      status: "completed",
      paymentMethod: "cash",
    },
    {
      id: "TRX-1006",
      date: "Jul 25, 2023",
      description: "Utility Bill - Electricity",
      amount: 8000,
      type: "expense",
      category: "utility",
      status: "completed",
      paymentMethod: "online",
    },
    {
      id: "TRX-1007",
      date: "Jul 26, 2023",
      description: "Booking Payment - ZT-1238",
      amount: 1200,
      type: "income",
      category: "booking",
      status: "pending",
      paymentMethod: "online",
    },
    {
      id: "TRX-1008",
      date: "Jul 26, 2023",
      description: "Staff Salary",
      amount: 15000,
      type: "expense",
      category: "salary",
      status: "completed",
      paymentMethod: "bank",
    },
  ],
} 